name: driver
description: Tedalal Driver-APP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.12
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  firebase_storage: ^10.2.12
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  awesome_notifications: ^0.6.21
  
  loader_overlay: ^2.0.5+1

  rxdart:
  google_maps_flutter: ^2.0.8
  latlong2: ^0.8.1
  location: ^4.3.0
  dio: ^4.0.0
  provider: ^6.0.2
  smooth_star_rating_nsafe: ^1.0.0+1
  flutter_svg: ^1.0.3
  cached_network_image:
  intl: ^0.17.0
  image_picker:
  flutter_image_compress:
  fluttertoast: ^8.0.9
  geolocator: ^8.2.0
  google_geocoding: ^0.2.0
  otp_text_field: ^1.1.3
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map/

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/cairo/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: fonts/cairo/Cairo-SemiBold.ttf
    - family: CairoBold
      fonts:
        - asset: fonts/cairo/Cairo-Bold.ttf
    - family: CairoBlack
      fonts:
        - asset: fonts/cairo/Cairo-Black.ttf
    - family: CairoLignt
      fonts:
        - asset: fonts/cairo/Cairo-Light.ttf
    - family: CairoExtraLignt
      fonts:
        - asset: fonts/cairo/Cairo-ExtraLight.ttf
